In [18]:
import sklearn

print(sklearn.__version__)

1.9.0

In [19]:
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
import numpy as np

from sklearn.datasets import fetch_california_housing


RANDOM_STATE = 42

sns.set_theme(style="whitegrid", context="notebook")

### Actividad 2

In [20]:
df_origin = fetch_california_housing(as_frame=True)
df = df_origin.frame.copy()

print(f"Dimensiones: {df.shape[0]} filas | {df.shape[1]} columnas")
print(f"Caracteristics: {df_origin.feature_names}")
df.head(5)

Dimensiones: 20640 filas | 9 columnas
Caracteristics: ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [22]:
df.dtypes

MedInc         float64
HouseAge       float64
AveRooms       float64
AveBedrms      float64
Population     float64
AveOccup       float64
Latitude       float64
Longitude      float64
MedHouseVal    float64
dtype: object

### Actividad 3

In [24]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
MedInc,20640.0,3.870671,1.899822,0.499900,2.563400,3.534800,4.743250,15.000100
HouseAge,20640.0,28.639486,12.585558,1.000000,18.000000,29.000000,37.000000,52.000000
AveRooms,20640.0,5.429000,2.474173,0.846154,4.440716,5.229129,6.052381,141.909091
AveBedrms,20640.0,1.096675,0.473911,0.333333,1.006079,1.048780,1.099526,34.066667
Population,20640.0,1425.476744,1132.462122,3.000000,787.000000,1166.000000,1725.000000,35682.000000
AveOccup,20640.0,3.070655,10.386050,0.692308,2.429741,2.818116,3.282261,1243.333333
Latitude,20640.0,35.631861,2.135952,32.540000,33.930000,34.260000,37.710000,41.950000
Longitude,20640.0,-119.569704,2.003532,-124.350000,-121.800000,-118.490000,-118.010000,-114.310000
MedHouseVal,20640.0,2.068558,1.153956,0.149990,1.196000,1.797000,2.647250,5.000010

### Diagnosticar calidad

In [29]:
pd.DataFrame({
    "tipo": df.dtypes.astype("str"),
    "nulos": df.isna().sum(),
    "infinitos": np.isinf(df.select_dtypes(include=np.number)).sum(),
    "unicos": df.nunique(),
    "latitud": len(df[~df["Latitude"].between(32, 42)]),
    "longitud": len(df[~df["Longitude"].between(-125, -114)]),
})

                tipo  nulos  infinitos  unicos  latitud  longitud
MedInc       float64      0          0   12928        0         0
HouseAge     float64      0          0      52        0         0
AveRooms     float64      0          0   19392        0         0
AveBedrms    float64      0          0   14233        0         0
Population   float64      0          0    3888        0         0
AveOccup     float64      0          0   18841        0         0
Latitude     float64      0          0     862        0         0
Longitude    float64      0          0     844        0         0
MedHouseVal  float64      0          0    3842        0         0

### Detectar extremos